# 1.¿"COMO SE LLAMA NUESTRO ROBOT?
name: Integracion Continua Nivel 5

# 2. ¿CUANDO SE DESPIERTA NUESTRO ROBOT?
on: 
   push:
     branches: ["main", "master"] # SE ACTIVA SI ALGUIEN HACE PUSH EN LA RAMA MAIN O MASTER
     pull_request:
      branches: ["main", "master"] # SE ACTIVA SI ALGUIEN PIDE UNIR SU CODIGO HACIA MAIN O MASTER

      # 3. ¿QUE  TRABAJOS (JOBS)HACE NUESTRO ROBOT CUANDO SE DESPIERTA?   
       jobs:
         build-and-test:
  # 4. ¿QUE COMPUTADORA LE PEDIMOS PRESTADA A GITHUB PARA QUE EJECUTE NUESTRO ROBOT?
           runs-on: ubuntu-latest # Pedimos un servidor con el sistema operativo Ubuntu (Linux)

           # 5.  ¿QUE PASOS (STEPS) EJECUTA NUESTRO ROBOT EN ESA COMPUTADORA?
           steps:

           # paso A: Descargar nuestro codigo al server prestado por GitHub
             - name: Descargar código fuente
               uses: actions/checkout@v4 # Acción oficial de GitHub para descargar el código del repositorio
           
           # paso B: Instalar el SDK  de C# .NET 8 en ese servidor
             - name: Instalar .NET 8
               uses: actions/setup-dotnet@v4 # Acción oficial de GitHub para instalar el SDK de .NET
               with:
                 dotnet-version: '8.0.x' # Especificamos la versión del SDK que queremos instalar
           
           # paso C: Descargar los Nugets (Entity framework Core,Automapper, etc.) necesarios para compilar nuestro codigo
             - name: Restaurar dependencias
               run: dotnet restore # Comando de .NET para descargar las dependencias del proyecto
           
           # paso D: Compilar nuestro codigo para verificar que no tenga errores de sintaxis
             - name: Compilar código
               run: dotnet build --configuration Release --no-restore # Comando de .NET para compilar el proyecto sin restaurar dependencias
           
           # paso E: Ejecutar las pruebas unitarias para verificar que nuestro codigo funciona correctamente
             - name: Ejecutar pruebas unitarias
               run: dotnet test --configuration Release --no-build --verbosity normal # Comando de .NET para ejecutar las pruebas sin compilar el proyecto
           
           # paso F: (Bonus nivel 5) Construir el contenedor de docker para verificar que se construye correctamente
             - name: Validar construcción de imagen de Docker
               run: docker build -t gestion-itm-api:latest -f src/Api/Dockerfile . # Comando de Docker para construir la imagen usando el Dockerfile en el directorio actual